#!/bin/bash
#
#请将此脚本加入到crontab定时任务中，如果你想一分钟检测一次应该这样写道：
#命令后面的>>管道是为了生成回显日志
#*/1 * * * * /bin/bash /home/liu/test/shell/Survive/false_ddns >>~/Survice.log
Domain=''
send(){
Sender=''
Password=''
To=''
Theme="你的域名($Domain)解析发生变动，请注意~"
Content="
当前域名:$Domain 
<br/>
解析结果为:$IPAddress 
<br/>
当前服务器IP地址为:$LocalIP 
<br/><hr>
<p><font color="red">系统检测到不匹配，特发送此邮件通知。</font><br/></p>
<input type="text" id="inputText" value="$LocalIP" />
<input type="button" id="btn" value="点击复制到剪切板" />
<script type="text/javascript">
    var btn = document.getElementById('btn');
    btn.addEventListener('click', function(){
        var inputText = document.getElementById('inputText');
        var currentFocus = document.activeElement;
        inputText.focus();
        inputText.setSelectionRange(0, inputText.value.length);
        document.execCommand('copy', true);
        currentFocus.focus();
    });
</script>
<a href="https://console.cloud.tencent.com/domain/mydomain"><font color="blue">点击此处跳转到腾讯云</font></a><br/>
"
/usr/local/bin/sendemail -f $Sender -t $To -s smtp.163.com -u $Theme -o message-content-type=html -o message-charset=utf8 -xu $Sender -xp $Password -m $Content
echo "Express=true" > ~/Express.txt
echo -e "提醒邮件发送完毕 \n }"
}
LocalIP=$(curl -s https://api.ip.la)
#`curl https://www.ipip.net/ip/ | grep '<input type="text" name="ip" value=' | awk 'BEGIN{FS="\""} NR<3{print $6}'`
IPAddress=`nslookup $Domain | grep "Address: " | awk 'BEGIN{FS=": "} NR=2{print $2}'`
echo ""
date
echo -e "{ \n Domain=$Domain \n LocalIP=$LocalIP \n IPAddress=$IPAddress"
if [ "$LocalIP" != "$IPAddress" ]
then
	Match=false
	echo "检测结果为不匹配，进入邮件程序."
	if [ -f "~/Express.txt" ]
	then
		echo -e "已经发送过邮件，退出程序。\n }"
		exit 1
	else
		send
	fi
else
	Math=true
	rm  ~/Express.txt
	echo -e "检测结果匹配，退出程序. \n }"
	exit 1
fi
